title:             JosephKim's Dev Blog
email:             chingu94@gmail.com
baseurl:           "/blog"
url:               "https://josephkim.github.io"

# Social Profiles
#twitter_username:  SBootstrap
#github_username:   BlackrockDigital
#facebook_username: StartBootstrap

# Build settings
remote_theme: BlackrockDigital/startbootstrap-clean-blog-jekyll
markdown:          kramdown
paginate:          5
paginate_path:     "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
